[package]
name = "brainfxxk"
version = "0.4.0"
authors = ["hi_go <me@clutte.red>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
